// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2uswldDx7BWOOQZqCzH9X9J6RxZU10BM',
    appId: '1:319206140002:web:2c72c869683a3a5bc0893b',
    messagingSenderId: '319206140002',
    projectId: 'my-cart-31d90',
    authDomain: 'my-cart-31d90.firebaseapp.com',
    storageBucket: 'my-cart-31d90.appspot.com',
    measurementId: 'G-V09V4S2MQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjKpain5M-9Tq4JJL_l8LB2up1pcYgPAM',
    appId: '1:319206140002:android:92fc2dda848271e2c0893b',
    messagingSenderId: '319206140002',
    projectId: 'my-cart-31d90',
    storageBucket: 'my-cart-31d90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKtxbeK1C3ikWUtLcooUeDau4vCZ9S058',
    appId: '1:319206140002:ios:c01a0c86b93f421ec0893b',
    messagingSenderId: '319206140002',
    projectId: 'my-cart-31d90',
    storageBucket: 'my-cart-31d90.appspot.com',
    iosBundleId: 'com.example.myCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKtxbeK1C3ikWUtLcooUeDau4vCZ9S058',
    appId: '1:319206140002:ios:c01a0c86b93f421ec0893b',
    messagingSenderId: '319206140002',
    projectId: 'my-cart-31d90',
    storageBucket: 'my-cart-31d90.appspot.com',
    iosBundleId: 'com.example.myCart',
  );
}
